ci:
  autofix_commit_msg: "ci: pre-commit auto fixes"
  autoupdate_commit_msg: "ci: pre-commit auto update"
  autoupdate_schedule: "monthly"
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        name: Check Blanket "#noqa"
      - id: python-check-blanket-type-ignore
        name: 'Check Blanket "#type:ignore"'
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        name: Upgrade Python Syntax
  - repo: https://github.com/crate-ci/typos
    rev: typos-v0.10.23
    hooks:
      - id: typos
        name: Check Typos
        args: []
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Format Source Code
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort Imports
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Type Check
        args: []
        # As `mypy` runs in an isolated environment, it is necessary to manually specify
        # some libraries of the current (poetry) environment for `mypy` to work properly.
        additional_dependencies:
          - arrow
          - httpx
          - hypothesis
          - importlib-metadata
          - playwright
          - pydantic
          - pytest
          - pytest-asyncio
          - starlette
          - types-dataclasses
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Lint
        additional_dependencies:
          - darglint
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-datetimez
          - flake8-debugger
          - flake8-docstrings
          - flake8-eradicate
          - flake8-print
          - pep8-naming
          - tryceratops
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        name: Check Commit Message
        stages: [commit-msg]
