services:
  rsserpent:
    container_name: rsserpent
    build: .
    ports:
      - "8000:8000"
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/app/cache
    volumes:
      - ./.cache:/app/cache
      - ./test-rsserpent.txt:/app/rsserpent.txt
