extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RSSerpent-Rev/RSSerpent
    - icon: fontawesome/brands/telegram
      link: https://t.me/rsserpent_rev
  version:
    provider: mike

extra_css:
  - __asset__/custom.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3

nav:
  - Introduction:
    - index.md
    - outline.md
    - faq.md
  - Usage:
    - usage/index.md
    - usage/router.md
  - Deployment:
    - deployment/index.md
    - deployment/deta.md
    - deployment/heroku.md
    - deployment/vercel.md
    - deployment/plugin.md
  - Contribution:
    - contribution/index.md
    - contribution/core.md
    - Plugin:
      - contribution/plugin/index.md
      - contribution/plugin/data.md
  - Plugin:
    - plugin/index.md

plugins:
  - git-revision-date
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            zh:
              Contribution: 贡献
              Deployment: 部署
              Introduction: 介绍
              Plugin: 插件
              Usage: 使用
      material_alternate: true
  - search:
      prebuild_index: true

remote_branch: doc
repo_name: RSSerpent-Rev/RSSerpent
repo_url: https://github.com/RSSerpent-Rev/RSSerpent

site_name: RSSerpent Docs
site_url: https://rsserpent-rev.github.io/RSSerpent/latest/

theme:
  favicon: 'https://ghproxy.imciel.com/https://raw.githubusercontent.com/RSSerpent-Rev/RSSerpent/master/docs/__asset__/logo-200.png'
  features:
    - header.autohide
    - navigation.expand
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/github
    logo: material/file-document-outline
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
