# Files
[nitpick.files.present]
".editorconfig" = ""
".gitignore" = ""
".pre-commit-config.yaml" = ""
"poetry.lock" = ""
"pyproject.toml" = ""
"tests/" = ""


# Pyproject.toml
["pyproject.toml".tool.poetry.dependencies]
python = "^3.10.0"

["pyproject.toml".tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-builtin
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-datetimez
    "DTZ",
    # flake8-debugger
    "T10",
    # eradicate
    "ERA",
    # flake8-print
    "T20",
    # pep8-naming
    "N",
    # tryceratops
    "TRY",
    # pygrep-hooks
    "PGH",
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

["pyproject.toml".tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

["pyproject.toml".tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
docstring-code-format = true

["pyproject.toml".tool.mypy]
plugins = ["pydantic.mypy"]
pretty = true
python_version = "3.10"
show_error_codes = true
strict = true

[["pyproject.toml".tool.mypy.overrides]]
module = ["pyquery.*"]
ignore_missing_imports = true

["pyproject.toml".tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true


["pyproject.toml".tool.nitpick]
cache = "1 day"


# Pre-Commit
[".pre-commit-config.yaml"]
default_stages = ["commit"]

[".pre-commit-config.yaml".ci]
autofix_commit_msg = "ci: pre-commit auto fixes"
autoupdate_commit_msg = "ci: pre-commit auto update"

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/andreoliwa/nitpick
    hooks:
      - id: nitpick-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    hooks:
      - id: typos
        args: []
  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
  - repo: https://github.com/commitizen-tools/commitizen
    hooks:
      - id: commitizen
        stages: [commit-msg]
"""
