name: Build Docker Image

on:
  pull_request:
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
  push:
    branches:
      - 'master'
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
    tags:
      - '*.*.*'

permissions:
  packages: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      IS_PRE_RELEASE: false
    steps:
      - uses: actions/checkout@v2
      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and Push"
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          tags: ghcr.io/rsserpent/rsserpent:master
