name: Build Docker Image

on:
  pull_request:
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
  push:
    branches:
      - 'master'
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
    tags:
      - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: "Login to Docker Hub"
        if: ${{ github.repository == 'RSSerpent/RSSerpent' }}
        uses: docker/login-action@v1
        with:
          username: queensferry
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Login to GitHub Container Registry"
        if: ${{ github.repository == 'RSSerpent/RSSerpent' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          load: true
          tags: rsserpent:master
      - name: "Minify Docker Images with `docker-slim`"
        run: |
          curl https://downloads.dockerslim.com/releases/1.36.3/dist_linux.tar.gz -o ds.tar.gz
          tar -xzvf ds.tar.gz --strip-component=1 && mv docker-slim* /usr/local/bin/
          docker-slim build \
            --include-path /home/app/.local/lib/python3.9/site-packages/certifi/cacert.pem \
            --tag queensferry/rsserpent:master \
            --tag ghcr.io/rsserpent/rsserpent:master \
            rsserpent:master
      - name: "Push Docker Images"
        if: ${{ github.repository == 'RSSerpent/RSSerpent' }}
        run: |
          docker push queensferry/rsserpent:master
          docker push ghcr.io/rsserpent/rsserpent:master
