name: Build Docker Image

on:
  pull_request:
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
  push:
    branches:
      - 'master'
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
    tags:
      - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      IS_PRE_RELEASE: false
    steps:
      - uses: actions/checkout@v2
      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build and Push"
        uses: docker/build-push-action@v2
        with:
          push: false
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
