name: Build Docker Image

on:
  pull_request:
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'rsserpent/**'
  push:
    branches:
      - 'master'
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'rsserpent/**'
    tags:
      - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      NOT_FORK_AND_NOT_PR: ${{ github.repository == 'RSSerpent/RSSerpent' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: "Login to Docker Hub"
        if: ${{ env.NOT_FORK_AND_NOT_PR }}
        uses: docker/login-action@v1
        with:
          username: queensferry
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Login to GitHub Container Registry"
        if: ${{ env.NOT_FORK_AND_NOT_PR }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: queensferry/rsserpent,ghcr.io/rsserpent/rsserpent
      - uses: docker/build-push-action@v2
        with:
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          tags: rsserpent:master
      - name: "Minify Docker Images with `docker-slim`"
        run: |
          curl https://downloads.dockerslim.com/releases/1.36.3/dist_linux.tar.gz -o ds.tar.gz
          tar -xzvf ds.tar.gz --strip-component=1 && mv docker-slim* /usr/local/bin/
          docker-slim build \
            --include-path /home/app/.local/lib/python3.9/site-packages/certifi/cacert.pem \
            --tag rsserpent.slim:master \
            rsserpent:master
          for tag in `echo "${{ steps.meta.outputs.tags }}"`; do
            docker tag rsserpent.slim:master $tag
          done
      - name: "Push Docker Images"
        if: ${{ env.NOT_FORK_AND_NOT_PR }}
        run: |
          for tag in `echo "${{ steps.meta.outputs.tags }}"`; do
            docker push $tag
          done
      - uses: bots-house/ghcr-delete-image-action@main
        if: ${{ env.NOT_FORK_AND_NOT_PR }}
        with:
          owner: rsserpent
          name: rsserpent
          token: ${{ secrets.PAT_TOKEN }}
          untagged-keep-latest: 10
      - uses: peter-evans/dockerhub-description@v2
        if: ${{ env.NOT_FORK_AND_NOT_PR }}
        with:
          username: queensferry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: queensferry/rsserpent
          short-description: ${{ github.event.repository.description }}
