name: Build Docker Image

on:
  pull_request:
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
  push:
    branches:
      - 'master'
    paths:
      - '.dockerignore'
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'rsserpent/**'
    tags:
      - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          load: true
          tags: ghcr.io/rsserpent/rsserpent:master
      - run: docker images
      - name: "Minify Docker Image with `docker-slim`"
        run: |
          curl https://downloads.dockerslim.com/releases/1.36.3/dist_linux.tar.gz -o ds.tar.gz
          tar -xzvf ds.tar.gz --strip-component=1 && mv docker-slim* /usr/local/bin/
          docker-slim build --include-path /home/app/.local/lib/python3.9/site-packages/certifi/cacert.pem --tag ghcr.io/rsserpent/rsserpent:master ghcr.io/rsserpent/rsserpent:master
          docker push ghcr.io/rsserpent/rsserpent:master
