name: Document

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/document.yaml'
      - 'mkdocs.yml'
      - 'poetry.lock'
      - 'docs/**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Setup Poetry"
        run: |
          pip install --upgrade pip
          pip install --user poetry
          poetry config virtualenvs.in-project true
      - uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: "Install Dependencies"
        run: poetry install --only docs
      - name: "Build Latest Document"
        run: |
          git fetch origin doc:doc
          poetry run mike deploy --push --update-aliases latest
