name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: "Setup Poetry"
        run: |
          pip install --upgrade pip
          pip install --user poetry
          poetry config virtualenvs.in-project true
      - name: "Check Version for Pre-releases"
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
          echo "IS_PRE_RELEASE=true" >> $GITHUB_ENV
      - name: "Build Stable Document"
        if: ${{ env.IS_PRE_RELEASE != true }}
        run: |
          poetry install --only docs
          git fetch origin doc:doc
          poetry run mike deploy --push --update-aliases stable
      - name: "Generate Release Note"
        run: awk "/^## $(poetry version --short)/{mark=1;next}/^## /{mark=0}mark" CHANGELOG.md > RELEASE.md
      - name: "Build Project"
        run: poetry build
      - name: "Create Release on GitHub"
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE.md
          files: dist/*
          fail_on_unmatched_files: true
          prerelease: ${{ env.IS_PRE_RELEASE }}
      - name: "Publish to PyPI"
        if: github.repository == 'RSSerpent-Rev/RSSerpent'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
